gcp pakcer

diff --git a/.github/workflows/packer.yml b/.github/workflows/packer.yml
--- a/.github/workflows/packer.yml
+++ b/.github/workflows/packer.yml
@@ -14,6 +14,15 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
+      - name: Set up Cloud SDK
+        uses: google-github-actions/auth@v2
+        with:
+          credentials_json: ${{ secrets.GCP_PACKER_CREDENTIALS }}
+          project_id: ${{secrets.GCP_PROJECT_ID}}
+
+      - name: Get credentials file path
+        run: echo $GOOGLE_APPLICATION_CREDENTIALS
+
       - name: Install Packer
         run: |
           curl -o packer.zip https://releases.hashicorp.com/packer/1.7.2/packer_1.7.2_linux_amd64.zip
@@ -36,10 +45,10 @@ jobs:
 
       - name: Run packer validate
         run: |
-          FILE="webapp-fork/api/packer/packer.pkr.hcl"
-          cd webapp-fork/api/packer
-          packer validate -var "project_id=${{secrets.GCP_PROJECT_ID}}" -var "credentials=$GOOGLE_APP_CREDENTIALS" -var "DB_PASSWORD=${{secrets.DB_PASSWORD}}" -var "DB_USERNAME=${{secrets.DB_USERNAME}}" -var "DB_DATABASE=${{secrets.DB_DATABASE}}" -var "PORT=${{secrets.PORT}}" -var "DB_HOST=${{secrets.DB_HOST}}" $FILE || exit 1
+          FILE="packer.pkr.hcl"
+          cd webapp-fork/api/packer/
+          packer validate -var "project_id=${{secrets.GCP_PROJECT_ID}}" -var "credentials=$GOOGLE_APPLICATION_CREDENTIALS" -var "DB_PASSWORD=${{secrets.DB_PASSWORD}}" -var "DB_USERNAME=${{secrets.DB_USERNAME}}" -var "DB_DATABASE=${{secrets.DB_DATABASE}}" -var "PORT=${{secrets.PORT}}" -var "DB_HOST=${{secrets.DB_HOST}}" $FILE || exit 1
           if [ $? -ne 0 ]; then
-            echo "packer validate failed to validate the packer template. Please fix the template."
-            exit 1
+              echo "packer validate failed to validate the packer template. Please fix the template."
+              exit 1
           fi
